package com.sample.rules
 
import java.util.*;
import javax.swing.*;
import java.awt.event.*;
import java.io.*;



// Funkcja zadająca pytanie i przyjmująca odpowiedź
function String askQuestion(Question q){
	JPanel panel = new JPanel(); // Tworzymy panel i layout
	panel.setLayout(new BoxLayout(panel, BoxLayout.PAGE_AXIS)); // elementy jeden pod drugim
    
    List<String> questionOptions = q.getQuestionOptions();
    List<String> questionOptionsTexts = q.getQuestionOptionsTexts();
    int numOfButtons = questionOptions.size();
    String questionText = q.getQuestionText();
    String answer = questionOptions.get(0);
    
    JLabel L1 = new JLabel(questionText); // Treść pytania
    panel.add(L1); 
        
    
    // Tworzymy Radio
    if(q.getChoiceType().equals("radio")){
	    ButtonGroup G1 = new ButtonGroup(); 
	    ArrayList<JRadioButton> radios = new ArrayList<JRadioButton>();
	    for(int i=0; i<numOfButtons; i++) {
	    	radios.add(new JRadioButton());
	    	radios.get(i).setText(questionOptionsTexts.get(i));
	    	panel.add(radios.get(i));
	    	G1.add(radios.get(i));
	    }
	    radios.get(0).setSelected(true);
	    
	    // Zbieramy odpowiedź
	    JOptionPane.showMessageDialog(null, panel, "Pytanie", JOptionPane.INFORMATION_MESSAGE);
	    for(int i=0; i<numOfButtons; i++) {
	    	if(radios.get(i).isSelected()){
	    		answer = questionOptions.get(i);
	    	}
	    }
	}
    return answer;
}

// Funkcja wyświetlająca rowiązanie
function void displaySolution(Solution s){
	JPanel panel = new JPanel(); // Tworzymy panel i layout
	panel.setLayout(new BoxLayout(panel, BoxLayout.PAGE_AXIS)); // elementy jeden pod drugim
    
    String solutionText = s.getSolutionText();
    
    JLabel L0 = new JLabel("Kanał do obejrzenia:");
    panel.add(L0);
    JLabel L1 = new JLabel(solutionText); // Treść rozwiązania
    panel.add(L1); 
        
    JOptionPane.showMessageDialog(null, panel, "Solution found!", JOptionPane.INFORMATION_MESSAGE);
}

// Nie działa
/*
query "getSolution"
	solution : Solution(isTrue == true)
end
*/

// Klasa pytania
declare Question
	questionName: String
	questionText: String
	choiceType: String
	questionOptions: List<String>
	questionOptionsTexts: List<String>
	answer: String
end

// Klasa rozwiązania
declare Solution
	solutionName: String
	solutionText: String
	isTrue: Boolean
end

// Wczytanie bazy wiedzy
rule "init"
	when
	then
		// Słownik pytań i odpowiedzi
		HashMap<String, String> resourceValues = new HashMap<String, String>();
		BufferedReader lang = new BufferedReader(new FileReader("src/main/resources/bazaWiedzy/englishQuestions.csv"));
		lang.readLine();
		lang.lines().forEach(line -> {
			String[] values = line.split(", ");
			resourceValues.put(values[0], values[1]);
		});
		
		// Słownik rozwiązań
		//HashMap<String, String> solutionValues = new HashMap<String, String>();
		BufferedReader sol = new BufferedReader(new FileReader("src/main/resources/bazaWiedzy/englishSolutions.csv"));
		sol.readLine();
		sol.lines().forEach(line -> {
			String[] values = line.split(", ");
			//solutionValues.put(values[0], values[1]);
			Solution s = new Solution(values[0], values[1], false);
			insert(s);
		});
		
		// Wczytanie Id i odpowiadających im wartości
		BufferedReader general = new BufferedReader(new FileReader("src/main/resources/bazaWiedzy/general.csv"));
		general.readLine();
		general.lines().forEach(line -> {
			String[] values = line.split(", ");
			int numOfOptions = Integer.parseInt(values[2]);
			ArrayList<String> questionOptions = new ArrayList<String>();
			ArrayList<String> questionOptionsTexts = new ArrayList<String>();
			for(int i=0; i<numOfOptions; i++){
				questionOptions.add(values[3+i]);
				questionOptionsTexts.add(resourceValues.get(values[3+i]));
			}
			Question q = new Question(values[0], resourceValues.get(values[0]), values[1], questionOptions, questionOptionsTexts, null);
			insert(q);
		});
end

////////////////////
// SZABLON REGUŁY //
////////////////////

rule "idPytania"
	when
		answered: Question(questionName == "idPytaniaNadrzędnego", answer == "idOdpowiedziNaPytanieNadrzędne")
		q: Question(questionName == "idPytania")
	then
		q.setAnswer(askQuestion(q));
		update(q);
end
////////////////////
////////////////////
////////////////////

////////////////////////////
// SZABLON REGUŁY KOŃCOWEJ//
////////////////////////////

rule "idRozwiązania"
	when
		answered: Question(questionName == "idPytaniaNadrzędnego", answer == "idOdpowiedziNaPytanieNadrzędne")
		s: Solution(solutionName == "idRozwiązania")
	then
		s.setIsTrue(true);
		update(s);
end
////////////////////////////
////////////////////////////
////////////////////////////

// Odczytanie rozwiązania
rule "showSolution"
	when
		s: Solution(isTrue == true)
	then
		displaySolution(s);
end

//////////////////
// Reguły pytań //
//////////////////

// MUSICIAN //

rule "startingQuestion"
	when
		q: Question(questionName == "startingQuestion")
	then
		q.setAnswer(askQuestion(q));
		update(q);
end

rule "musicianType"
	when
		answered: Question(questionName == "startingQuestion", answer == "musician")
		q: Question(questionName == "musicianType")
	then
		q.setAnswer(askQuestion(q));
		update(q);
end

rule "necessaryExist"
	when
		answered: Question(questionName == "musicianType", answer == "muggle")
		q: Question(questionName == "necessaryExist")
	then
		q.setAnswer(askQuestion(q));
		update(q);
end

rule "lostShow"
	when
		answered: Question(questionName == "necessaryExist", answer == "yesExist")
		q: Question(questionName == "lostShow")
	then
		q.setAnswer(askQuestion(q));
		update(q);
end

rule "couplesMusic"
	when
		answered: Question(questionName == "lostShow", answer == "noShow")
		q: Question(questionName == "couplesMusic")
	then
		q.setAnswer(askQuestion(q));
		update(q);
end

rule "easilyOffended"
	when
		answered: Question(questionName == "couplesMusic", answer == "noCouples")
		q: Question(questionName == "easilyOffended")
	then
		q.setAnswer(askQuestion(q));
		update(q);
end

rule "likeUkuleles"
	when
		answered: Question(questionName == "easilyOffended", answer == "yesOffended")
		q: Question(questionName == "likeUkuleles")
	then
		q.setAnswer(askQuestion(q));
		update(q);
end

rule "mellowOrRock"
	when
		answered: Question(questionName == "likeUkuleles", answer == "noUkuleles")
		q: Question(questionName == "mellowOrRock")
	then
		q.setAnswer(askQuestion(q));
		update(q);
end

rule "normalOrStrangeLyrics"
	when
		answered: Question(questionName == "mellowOrRock", answer == "rock")
		q: Question(questionName == "normalOrStrangeLyrics")
	then
		q.setAnswer(askQuestion(q));
		update(q);
end

rule "pianoOrGuitar"
	when
		answered: Question(questionName == "normalOrStrangeLyrics", answer == "normalLyrics")
		q: Question(questionName == "pianoOrGuitar")
	then
		q.setAnswer(askQuestion(q));
		update(q);
end

rule "cyrusOrRandom"
	when
		answered: Question(questionName == "normalOrStrangeLyrics", answer == "strangeLyrics")
		q: Question(questionName == "cyrusOrRandom")
	then
		q.setAnswer(askQuestion(q));
		update(q);
end

rule "nerdyOrNormalSongs"
	when
		answered: Question(questionName == "likeUkuleles", answer == "yesUkuleles")
		q: Question(questionName == "nerdyOrNormalSongs")
	then
		q.setAnswer(askQuestion(q));
		update(q);
end

rule "wizardRock"
	when
		answered: Question(questionName == "musicianType", answer == "wizard")
		q: Question(questionName == "wizardRock")
	then
		q.setAnswer(askQuestion(q));
		update(q);
end

rule "likeElectronica"
	when
		answered: Question(questionName == "couplesMusic", answer == "yesCouples")
		q: Question(questionName == "likeElectronica")
	then
		q.setAnswer(askQuestion(q));
		update(q);
end

rule "livePerformances"
	when
		answered: Question(questionName == "wizardRock", answer == "awesome")
		q: Question(questionName == "livePerformances")
	then
		q.setAnswer(askQuestion(q));
		update(q);
end

rule "tooCheap"
	when
		answered: Question(questionName == "livePerformances", answer == "noLive")
		q: Question(questionName == "tooCheap")
	then
		q.setAnswer(askQuestion(q));
		update(q);
end

rule "whompingWillow"
	when
		answered: Question(questionName == "tooCheap", answer == "noTooCheap")
		q: Question(questionName == "whompingWillow")
	then
		q.setAnswer(askQuestion(q));
		update(q);
end

/////////////
// VLOGGER //
/////////////

rule "collabOrSingle"
	when
		answered: Question(questionName == "startingQuestion", answer == "vlogger")
		q: Question(questionName == "collabOrSingle")
	then
		q.setAnswer(askQuestion(q));
		update(q);
end

rule "newOrOldVideos"
	when
		answered: Question(questionName == "collabOrSingle", answer == "collab")
		q: Question(questionName == "newOrOldVideos")
	then
		q.setAnswer(askQuestion(q));
		update(q);
end

rule "relationships"
	when
		answered: Question(questionName == "newOrOldVideos", answer == "new")
		q: Question(questionName == "relationships")
	then
		q.setAnswer(askQuestion(q));
		update(q);
end

rule "doctorWho"
	when
		answered: Question(questionName == "relationships", answer == "sick")
		q: Question(questionName == "doctorWho")
	then
		q.setAnswer(askQuestion(q));
		update(q);
end

rule "howManyWatch"
	when
		answered: Question(questionName == "doctorWho", answer == "noDoctor")
		q: Question(questionName == "howManyWatch")
	then
		q.setAnswer(askQuestion(q));
		update(q);
end

rule "shortOrTall"
	when
		answered: Question(questionName == "howManyWatch", answer == "two")
		q: Question(questionName == "shortOrTall")
	then
		q.setAnswer(askQuestion(q));
		update(q);
end

rule "tallGirlsOrBoys"
	when
		answered: Question(questionName == "shortOrTall", answer == "tall")
		q: Question(questionName == "tallGirlsOrBoys")
	then
		q.setAnswer(askQuestion(q));
		update(q);
end

rule "whatKindOfAccent"
	when
		answered: Question(questionName == "collabOrSingle", answer == "single")
		q: Question(questionName == "whatKindOfAccent")
	then
		q.setAnswer(askQuestion(q));
		update(q);
end

rule "canadaIsCool"
	when
		answered: Question(questionName == "whatKindOfAccent", answer == "otherAccent")
		q: Question(questionName == "canadaIsCool")
	then
		q.setAnswer(askQuestion(q));
		update(q);
end

rule "whichIsFunnier"
	when
		answered: Question(questionName == "canadaIsCool", answer == "noCanada")
		q: Question(questionName == "whichIsFunnier")
	then
		q.setAnswer(askQuestion(q));
		update(q);
end










































////////////////////
// REGUŁY KOŃCOWE //
////////////////////

// MUSICIAN //

rule "necessaryExistNo"
	when
		answered: Question(questionName == "necessaryExist", answer == "noExist")
		s: Solution(solutionName == "necessaryExistNo")
	then
		s.setIsTrue(true);
		update(s);
end

rule "easilyOffendedNo"
	when
		answered: Question(questionName == "easilyOffended", answer == "noOffended")
		s: Solution(solutionName == "easilyOffendedNo")
	then
		s.setIsTrue(true);
		update(s);
end

rule "mellowOrRockMellow"
	when
		answered: Question(questionName == "mellowOrRock", answer == "mellow")
		s: Solution(solutionName == "mellowOrRockMellow")
	then
		s.setIsTrue(true);
		update(s);
end

rule "pianoOrGuitarPiano"
	when
		answered: Question(questionName == "pianoOrGuitar", answer == "piano")
		s: Solution(solutionName == "pianoOrGuitarPiano")
	then
		s.setIsTrue(true);
		update(s);
end

rule "pianoOrGuitarGuitar"
	when
		answered: Question(questionName == "pianoOrGuitar", answer == "guitar")
		s: Solution(solutionName == "pianoOrGuitarGuitar")
	then
		s.setIsTrue(true);
		update(s);
end

rule "cyrusOrRandomCyrus"
	when
		answered: Question(questionName == "cyrusOrRandom", answer == "cyrus")
		s: Solution(solutionName == "cyrusOrRandomCyrus")
	then
		s.setIsTrue(true);
		update(s);
end

rule "cyrusOrRandomRandom"
	when
		answered: Question(questionName == "cyrusOrRandom", answer == "random")
		s: Solution(solutionName == "cyrusOrRandomRandom")
	then
		s.setIsTrue(true);
		update(s);
end

rule "nerdyOrNormalSongsNormal"
	when
		answered: Question(questionName == "nerdyOrNormalSongs", answer == "normalSongs")
		s: Solution(solutionName == "nerdyOrNormalSongsNormal")
	then
		s.setIsTrue(true);
		update(s);
end

rule "nerdyOrNormalSongsNerdy"
	when
		answered: Question(questionName == "nerdyOrNormalSongs", answer == "nerdySongs")
		s: Solution(solutionName == "nerdyOrNormalSongsNerdy")
	then
		s.setIsTrue(true);
		update(s);
end

rule "likeElectronicaYes"
	when
		answered: Question(questionName == "likeElectronica", answer == "yesElectronica")
		s: Solution(solutionName == "likeElectronicaYes")
	then
		s.setIsTrue(true);
		update(s);
end

rule "likeElectronicaNo"
	when
		answered: Question(questionName == "likeElectronica", answer == "noElectronica")
		s: Solution(solutionName == "likeElectronicaNo")
	then
		s.setIsTrue(true);
		update(s);
end

rule "lostShowYes"
	when
		answered: Question(questionName == "lostShow", answer == "yesShow")
		s: Solution(solutionName == "lostShowYes")
	then
		s.setIsTrue(true);
		update(s);
end

rule "wizardRockWeird"
	when
		answered: Question(questionName == "wizardRock", answer == "weird")
		s: Solution(solutionName == "wizardRockWeird")
	then
		s.setIsTrue(true);
		update(s);
end

rule "livePerformancesYes"
	when
		answered: Question(questionName == "livePerformances", answer == "yesLive")
		s: Solution(solutionName == "livePerformancesYes")
	then
		s.setIsTrue(true);
		update(s);
end

rule "tooCheapYes"
	when
		answered: Question(questionName == "tooCheap", answer == "yesTooCheap")
		s: Solution(solutionName == "tooCheapYes")
	then
		s.setIsTrue(true);
		update(s);
end

rule "whompingWillowYes"
	when
		answered: Question(questionName == "whompingWillow", answer == "yesWillow")
		s: Solution(solutionName == "whompingWillowYes")
	then
		s.setIsTrue(true);
		update(s);
end

rule "whompingWillowNo"
	when
		answered: Question(questionName == "whompingWillow", answer == "noWillow")
		s: Solution(solutionName == "whompingWillowNo")
	then
		s.setIsTrue(true);
		update(s);
end

/////////////
// VLOGGER //
/////////////

rule "newOrOldVideosOld"
	when
		answered: Question(questionName == "newOrOldVideos", answer == "old")
		s: Solution(solutionName == "newOrOldVideosOld")
	then
		s.setIsTrue(true);
		update(s);
end

rule "relationshipsHappy"
	when
		answered: Question(questionName == "relationships", answer == "happy")
		s: Solution(solutionName == "relationshipsHappy")
	then
		s.setIsTrue(true);
		update(s);
end

rule "doctorWhoYes"
	when
		answered: Question(questionName == "doctorWho", answer == "yesDoctor")
		s: Solution(solutionName == "doctorWhoYes")
	then
		s.setIsTrue(true);
		update(s);
end

rule "howManyWatchFive"
	when
		answered: Question(questionName == "howManyWatch", answer == "five")
		s: Solution(solutionName == "howManyWatchFive")
	then
		s.setIsTrue(true);
		update(s);
end

rule "shortOrTallShort"
	when
		answered: Question(questionName == "shortOrTall", answer == "short")
		s: Solution(solutionName == "shortOrTallShort")
	then
		s.setIsTrue(true);
		update(s);
end

rule "tallGirlsOrBoysGirls"
	when
		answered: Question(questionName == "tallGirlsOrBoys", answer == "tallGirls")
		s: Solution(solutionName == "tallGirlsOrBoysGirls")
	then
		s.setIsTrue(true);
		update(s);
end

rule "tallGirlsOrBoysBoys"
	when
		answered: Question(questionName == "tallGirlsOrBoys", answer == "tallBoys")
		s: Solution(solutionName == "tallGirlsOrBoysBoys")
	then
		s.setIsTrue(true);
		update(s);
end