package com.sample.rules
 
import java.util.*;
import javax.swing.*;
import java.awt.event.*;
import java.util.*;

// Funkcja zadaj¹ca pytanie i przyjmuj¹ca odpowiedŸ
function String askQuestion(Question q){
	JPanel panel = new JPanel(); // Tworzymy panel i layout
	panel.setLayout(new BoxLayout(panel, BoxLayout.PAGE_AXIS)); // elementy jeden pod drugim
    
    List<String> questionOptions = q.getQuestionOptions();
    int numOfButtons = questionOptions.size();
    String questionText = q.getQuestionText();
    String answer = questionOptions.get(0);
    
    JLabel L1 = new JLabel(questionText); // Treœæ pytania
    panel.add(L1); 
        
    // Tworzymy Radio
    ButtonGroup G1 = new ButtonGroup(); 
    ArrayList<JRadioButton> radios = new ArrayList<JRadioButton>();
    for(int i=0; i<numOfButtons; i++) {
    	radios.add(new JRadioButton());
    	radios.get(i).setText(questionOptions.get(i));
    	panel.add(radios.get(i));
    	G1.add(radios.get(i));
    }
    radios.get(0).setSelected(true);
    
    // Zbieramy odpowiedŸ
    JOptionPane.showMessageDialog(null, panel);
    for(int i=0; i<numOfButtons; i++) {
    	if(radios.get(i).isSelected()){
    		answer = questionOptions.get(i);
    	}
    }
    return answer;
}

// Klasa pytania
declare Question
	questionText: String
	questionOptions: List<String>
	choiceType: ChoiceTypes //TODO
	answer: String
end

// Enumerator Radio/Checkbox
declare enum ChoiceTypes
	RADIO, CHECK;
end

rule "test init"
	when
	then
		insert(new Question("What kind of channel do you want to watch?", Arrays.asList("Musician", "Vlogger"), ChoiceTypes.RADIO, ""));
end

rule "test print"
	when
		q: Question(choiceType == ChoiceTypes.RADIO)
	then
		System.out.println(q.getChoiceType());
end

rule "test gui"
	when
		q: Question(answer == "")
	then
		q.setAnswer(askQuestion(q));
		update(q);
end